name: Waka Readme

on:
  schedule:
    - cron: '0 12,0 * * *'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: waka-readme-stats
      uses: athul/waka-readme@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
        TIME_RANGE: last_6_months
        COMMIT_MESSAGE: Updated the Readme
